/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasi;

import DB.konek;
import java.awt.Frame;
import java.io.UnsupportedEncodingException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.Const;
import kelas.operasiData;

/**
 *
 * @author ISMYNR
 */
public class Transaksi_Operasi_CekSaldo extends javax.swing.JPanel {

    /**
     * Creates new form Transaksi_Operasi_CekSaldo
     */
    public Transaksi_Operasi_CekSaldo() {
        initComponents();
        cekSaldo();
        setTable();
        dataMasukTabel("");
        setTableSimpanan();
        lb_saldo.setVisible(false);
        txtf_saldo.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_table_cari = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        txtf_frameCariAnggota = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_cari_anggota = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lb_judul = new javax.swing.JLabel();
        btn_cariAnggota = new javax.swing.JButton();
        txtf_saldo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txta_info1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_info2 = new javax.swing.JTextArea();
        lb_saldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_simpanan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lb_judul1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lb_simpanan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lb_pengeluaran = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        lb_jml_pinjaman = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lb_pinjaman = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        lb_dana_tersisa = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel10.setPreferredSize(new java.awt.Dimension(752, 50));

        txtf_frameCariAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_frameCariAnggotaKeyReleased(evt);
            }
        });

        jLabel15.setText("CARI");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtf_frameCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtf_frameCariAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        frame_table_cari.getContentPane().add(jPanel10, java.awt.BorderLayout.PAGE_START);

        tb_cari_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_cari_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_cari_anggotaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_cari_anggota);

        frame_table_cari.getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(583, 200));

        lb_judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_judul.setForeground(new java.awt.Color(51, 51, 51));
        lb_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_judul.setText("Buku Simpanan Anggota");
        lb_judul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_cariAnggota.setText("Pilih Anggota");
        btn_cariAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariAnggotaActionPerformed(evt);
            }
        });

        txtf_saldo.setEditable(false);
        txtf_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_saldoActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBorder(null);

        txta_info1.setEditable(false);
        txta_info1.setColumns(20);
        txta_info1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txta_info1.setLineWrap(true);
        txta_info1.setRows(5);
        txta_info1.setWrapStyleWord(true);
        txta_info1.setBorder(null);
        jScrollPane4.setViewportView(txta_info1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        txta_info2.setEditable(false);
        txta_info2.setColumns(20);
        txta_info2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txta_info2.setLineWrap(true);
        txta_info2.setRows(5);
        txta_info2.setWrapStyleWord(true);
        txta_info2.setBorder(null);
        jScrollPane2.setViewportView(txta_info2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel7);

        lb_saldo.setText("Saldo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lb_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_saldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cariAnggota)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cariAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtf_saldo)
                    .addComponent(lb_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tb_simpanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_simpanan);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lb_judul1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_judul1.setForeground(new java.awt.Color(51, 51, 51));
        lb_judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_judul1.setText("SALDO KESELURUHAN");
        lb_judul1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(281, 110));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_simpanan.setFont(new java.awt.Font("Tough Love", 1, 18)); // NOI18N
        lb_simpanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lb_simpanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 261, 88));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel13.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 110));

        jPanel11.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMPANAN");
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel11.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel14.setPreferredSize(new java.awt.Dimension(281, 110));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_pengeluaran.setFont(new java.awt.Font("Tough Love", 1, 18)); // NOI18N
        lb_pengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lb_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 261, 88));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 110));

        jPanel12.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PENGELUARAN");
        jLabel2.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel12.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel12);

        jPanel15.setPreferredSize(new java.awt.Dimension(562, 156));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setPreferredSize(new java.awt.Dimension(281, 110));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_jml_pinjaman.setFont(new java.awt.Font("Tough Love", 1, 18)); // NOI18N
        lb_jml_pinjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lb_jml_pinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 261, 88));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel17.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 110));

        jPanel16.add(jPanel17, java.awt.BorderLayout.PAGE_END);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("JUMLAH PINJAMAN");
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel16.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setPreferredSize(new java.awt.Dimension(281, 110));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_pinjaman.setFont(new java.awt.Font("Tough Love", 1, 18)); // NOI18N
        lb_pinjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel19.add(lb_pinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 261, 88));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel19.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 110));

        jPanel18.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PINJAMAN");
        jLabel8.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel18.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel18);

        jPanel20.setPreferredSize(new java.awt.Dimension(562, 156));
        jPanel20.setLayout(new java.awt.GridLayout());

        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setPreferredSize(new java.awt.Dimension(281, 110));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_dana_tersisa.setFont(new java.awt.Font("Tough Love", 1, 18)); // NOI18N
        lb_dana_tersisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel22.add(lb_dana_tersisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 540, 88));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel22.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 110));

        jPanel21.add(jPanel22, java.awt.BorderLayout.PAGE_END);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DANA TERSISA");
        jLabel10.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel21.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel21);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_judul1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel model;
    private DefaultTableModel modelSimpanan;
    private operasiData odata;
    private konek koneksi;
    private String id_angg; 
    
    private void setTable(){
        Object[] field = new Object[]{"ID", "Nama", "NIK", "lahir", "JK", "ID Pekerjaan", "No Hp", "Alamat", 
                    "Email","Dibuat", "Diubah"};
        model = new DefaultTableModel(field, 0);
        tb_cari_anggota.setModel(model);
        tb_cari_anggota.setRowHeight(30);
    }
    
    private void dataMasukTabel(String key){
        odata = new operasiData();
        model.getDataVector().removeAllElements();
        ResultSet rs;
        String W = "";
        try {
            koneksi = new konek();
            if(!key.equals("")){
                W = "WHERE id LIKE '%"+key+"%' OR nama LIKE '%"+key+"%' OR nik LIKE '%"+Const.encrypt(key)+"%' "
                        + "OR tgl_lahir LIKE '%"+key+"%' OR jk LIKE '%"+key+"%' OR pekerjaan LIKE '%"+key+"%' OR no_hp LIKE '%"+Const.encrypt(key)+"%' "
                        + "OR alamat LIKE '%"+Const.encrypt(key)+"%' OR email LIKE'%"+Const.encrypt(key)+"%' "
                        + "OR created_at LIKE '%"+key+"%' OR updated_at LIKE '%"+key+"%'";
            }
            rs = koneksi.eksekusiSelect("SELECT * FROM anggota "+W+"");
            while(rs.next()){
                String decNik = Const.decrypt(rs.getString(3));
                String decNo_hp = Const.decrypt(rs.getString(7));
                String decAlamat = Const.decrypt(rs.getString(8));
                String decEmail = Const.decrypt(rs.getString(9));
                Object[] data = {rs.getString(1), rs.getString(2), decNik, rs.getString(4), 
                    rs.getString(5), rs.getString(6), decNo_hp, decAlamat, decEmail, 
                    rs.getString(10), rs.getString(11)};
                model.addRow(data);
            }
        } catch (SQLException | UnsupportedEncodingException e) {JOptionPane.showMessageDialog(null, "dataMasukTabel : "+e);}
    }
    private void setTableSimpanan(){
        Object[] field = new Object[]{"ID", "Jumlah Simpan", "Jenis Simpan",
                    "Tanggal Simpan", "Keterangan"};
        modelSimpanan = new DefaultTableModel(field, 0);
        tb_simpanan.setModel(modelSimpanan);
        tb_simpanan.setRowHeight(30);
    }
    
    private void dataMasukTabelSimpanan(String key){
        odata = new operasiData();
        modelSimpanan.getDataVector().removeAllElements();
        ResultSet rs;
        String W = "";
        try {
            koneksi = new konek();
            if(!key.equals("")){
                W = "AND id LIKE '"+key+"' OR jml_simpan LIKE '"+key+"' OR "
                                + "jns_simpan LIKE '"+key+"' OR tgl_simpan LIKE '"+key+"' OR ket LIKE '"+key+"'";
            }
            rs = koneksi.eksekusiSelect("SELECT * FROM simpanan WHERE id_angg='"+id_angg+"' "+W+"");
            while(rs.next()){
                Object[] data = {rs.getString(1), rs.getString(4), 
                            rs.getString(5), rs.getString(6), rs.getString(7)};
                modelSimpanan.addRow(data);
            }
        } catch (SQLException e) {JOptionPane.showMessageDialog(null, "dataMasukTabel : "+e);}
    }
    
    
    private void btn_cariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariAnggotaActionPerformed
        setTable();
        dataMasukTabel("");
        frame_table_cari.setExtendedState(Frame.MAXIMIZED_BOTH);
        frame_table_cari.setVisible(true);
    }//GEN-LAST:event_btn_cariAnggotaActionPerformed

    private void txtf_frameCariAnggotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_frameCariAnggotaKeyReleased
        dataMasukTabel(txtf_frameCariAnggota.getText());
    }//GEN-LAST:event_txtf_frameCariAnggotaKeyReleased

    private void tb_cari_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_cari_anggotaMouseClicked
        odata = new operasiData();
        int getRow = tb_cari_anggota.getSelectedRow();
        String id_anggota = (String)tb_cari_anggota.getValueAt(getRow, 0);
        String nama_anggota = (String)tb_cari_anggota.getValueAt(getRow, 1);
        String nik = (String)tb_cari_anggota.getValueAt(getRow, 2);
        String no_hp = (String)tb_cari_anggota.getValueAt(getRow, 6);
        String email = (String)tb_cari_anggota.getValueAt(getRow, 8);
        lb_saldo.setVisible(true);
        txtf_saldo.setVisible(true);
        if (!odata.saldoSimpananAnggota(id_anggota).equals("")) {
            txtf_saldo.setText(odata.saldoSimpananAnggota(id_anggota));
            id_angg = id_anggota;
            dataMasukTabelSimpanan("");
        }else{
            txtf_saldo.setText("Belum ada simpanan");
        } 
        String a = "";
        //int getRowSimpanan = tb_simpanan.getSelectedRow();
        //String jns_simpan = (String)tb_simpanan.getValueAt(getRowSimpanan, 2);
        try {
            koneksi = new konek();
            ResultSet rs = koneksi.eksekusiSelect("SELECT * FROM jenis_simpanan");
            while(rs.next()){
                if (a.equals("")) {
                    a = rs.getString(2) + " : " + odata.itemSimpananAnggota(id_anggota, rs.getString(1))+"\n";
                }else{
                    a += rs.getString(2) + " : " + odata.itemSimpananAnggota(id_anggota, rs.getString(1))+"\n";
                }
            }
            txta_info1.setText("ID \t: "+id_anggota+
                                "\nNAMA \t: "+nama_anggota+
                                "\nNIK \t: "+nik+
                                "\nNO HP \t: "+no_hp+
                                "\nEMAIL \t: "+email);
            txta_info2.setText(a);
        } catch (SQLException ex) {}
        
        frame_table_cari.setVisible(false);
        tb_simpanan.clearSelection();
    }//GEN-LAST:event_tb_cari_anggotaMouseClicked

    private void txtf_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_saldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cariAnggota;
    private javax.swing.JFrame frame_table_cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb_dana_tersisa;
    private javax.swing.JLabel lb_jml_pinjaman;
    private javax.swing.JLabel lb_judul;
    private javax.swing.JLabel lb_judul1;
    private javax.swing.JLabel lb_pengeluaran;
    private javax.swing.JLabel lb_pinjaman;
    private javax.swing.JLabel lb_saldo;
    private javax.swing.JLabel lb_simpanan;
    private javax.swing.JTable tb_cari_anggota;
    private javax.swing.JTable tb_simpanan;
    private javax.swing.JTextArea txta_info1;
    private javax.swing.JTextArea txta_info2;
    private javax.swing.JTextField txtf_frameCariAnggota;
    private javax.swing.JTextField txtf_saldo;
    // End of variables declaration//GEN-END:variables

    //CEK SALDO KESELURUHAN KOPERASI
    private void cekSaldo(){
        try {
            koneksi = new konek();
            ResultSet rs;
            String simpanan = "SELECT SUM(jml_simpan) FROM simpanan";
            String pengeluaran = "SELECT SUM(jml_pengl) FROM pengeluaran";
            String jumlah_pinjaman = "SELECT COUNT(*) FROM pinjaman";
            String pinjaman = "SELECT SUM(sisa_angsur) FROM angsuran_pinjaman WHERE status_angsur='On'";
            rs = koneksi.eksekusiSelect(simpanan);
            if(rs.next()){
                simpanan = rs.getString(1) == null ? "0" : rs.getString(1);
            }
            rs = koneksi.eksekusiSelect(pengeluaran);
            if(rs.next()){
                pengeluaran = rs.getString(1) == null ? "0" : rs.getString(1);
            }
            rs = koneksi.eksekusiSelect(jumlah_pinjaman);
            if(rs.next()){
                jumlah_pinjaman = rs.getString(1) == null ? "0" : rs.getString(1);
            }
            rs = koneksi.eksekusiSelect(pinjaman);
            if(rs.next()){
                pinjaman = rs.getString(1) == null ? "0" : rs.getString(1);
            }
            lb_simpanan.setText(simpanan);
            lb_pengeluaran.setText(pengeluaran);
            lb_jml_pinjaman.setText(jumlah_pinjaman);
            lb_pinjaman.setText(pinjaman);
            int danaTersisa = (Integer.parseInt(simpanan)-Integer.parseInt(pengeluaran)-Integer.parseInt(pinjaman));
            lb_dana_tersisa.setText(""+danaTersisa);
        } catch (SQLException ex) {
            
        }
    }

}

